# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=utodo
      - PGPORT=5432
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080