# Generated by Django 4.1.5 on 2023-11-19 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('Term Tests', 'Term Tests'), ('Assignments', 'Assignments'), ('Projects', 'Projects'), ('Homework', 'Homework'), ('Quizzes', 'Quizzes'), ('Final Exam', 'Final Exam'), ('Others', 'Others')], max_length=11)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade_now', models.FloatField(default=0.0)),
                ('grade_total', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_counted', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course.course')),
            ],
        ),
    ]
