# Generated by Django 4.1.5 on 2023-11-19 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('university', models.CharField(blank=True, default='University of Toronto', max_length=100)),
                ('grade_now', models.FloatField(blank=True, default=0.0)),
                ('grade_total', models.FloatField(blank=True, default=0.0)),
                ('year', models.IntegerField(blank=True, default=2023)),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Summer', 'Summer')], default='Fall', max_length=6)),
                ('is_public', models.BooleanField(default=False)),
                ('is_on_list', models.BooleanField(default=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_courses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
