# Generated by Django 4.1.5 on 2023-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_is_public_alter_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='grade',
            new_name='grade_now',
        ),
        migrations.AddField(
            model_name='course',
            name='grade_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='is_show_grade',
            field=models.BooleanField(default=False),
        ),
    ]
