# Generated by Django 4.1.5 on 2023-11-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_grade_course_grade_now_course_grade_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_show_grade',
        ),
    ]
