# Generated by Django 4.1.5 on 2023-11-13 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_remove_course_is_show_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
