# Generated by Django 4.1.5 on 2023-11-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_on_list',
            field=models.BooleanField(default=True),
        ),
    ]
