# Generated by Django 4.1.5 on 2023-11-12 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(choices=[('Term Tests', 'Term Tests'), ('Assignments', 'Assignments'), ('Projects', 'Projects'), ('Homework', 'Homework'), ('Quizzes', 'Quizzes'), ('Final Exam', 'Final Exam'), ('Others', 'Others')], max_length=11)),
                ('grade', models.FloatField(default=1.0)),
                ('count', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='course.course')),
            ],
        ),
    ]
