# Generated by Django 4.1.5 on 2023-11-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_chosen',
            new_name='is_counted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='grade',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='grade_now',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='grade_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
